language: node_js
node_js:
- node
before_install:
- pip install --user codecov
after_success:
- codecov --file coverage/lcov.info --disable search
deploy:
  provider: npm
  email: mickperkins@gmail.com
  api_key:
    secure: v3TOuHWmpYkj5XoSCNgDOdeEnXtaP5GfkdgKfcqQxL+A0UOmK7GjQKTBSnQzpLGoLupxLhGJojRpWHxR/C7nzohNLo+pJkqTP8cMyV0UCJRw59DLLuD0Cl/VRXGZ8kLCv1GRoiF6LsMCEJF4yu4nbJ0CicfadmizYyT9bQaO58I/vlmgYFcPA/FCe/jkziz4V0TH+MzJ8VIKpPXej3eQWMrIU145UYewqjP84xeRzvqBm7iMr40oOcPalF7bTg45A6xGkxFjZTyNNFga2BxlNmx5xVTFW1fyPDKqUdilss38EJAGAKuGMfa+3GgaTf+Uyk2fCeb73/+73pspbtU6OfAJjsamhpVzzG9IHfJNdkQegtsN/b8/NMWWmG7LHdeCGhcJ9r+p7/0lKTy0Fu4VvJgX+ECAreRbEBDyWnYWbR/DQosoUTIJk0dFS4URr4lxsVoxcNQysFDXgrcj9k4OsgHRZXRpNNouNGmJ7aR/ThnwzNjvRo70C1AJxOkv4eDjv9r2lpWTw0Zl6gq/bv1HhJDVkYTylekGYKlsycKxUXRjAL8kwVS0ObfUpsg63Cp9dOzgzZSHFNVI4GEothctLn29Ao+mW6fMs5qZZxBn/dHSsNv7qoiKqcY/VnWaAiVZo3S3t2cbAYMiu1XbhWYmRJZ97lLx40eOUyId8hYFzZw=
  on:
    branch: master